name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.18.7 <3.0.0"

dependencies:
  args: ^2.0.0
  path: ^1.8.3
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  tiny_storage: ^1.0.1

dev_dependencies:
  http: ^0.13.0
  test: ^1.15.0
  very_good_analysis: ^3.1.0
